// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: endpoints.sql

package infra

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEndpoint = `-- name: GetEndpoint :one
SELECT slug, created_at
FROM endpoints
WHERE slug = $1
`

func (q *Queries) GetEndpoint(ctx context.Context, slug string) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpoint, slug)
	var i Endpoint
	err := row.Scan(&i.Slug, &i.CreatedAt)
	return i, err
}

const saveEndpoint = `-- name: SaveEndpoint :exec
INSERT INTO endpoints (slug, created_at)
VALUES ($1, $2)
`

type SaveEndpointParams struct {
	Slug      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) SaveEndpoint(ctx context.Context, arg SaveEndpointParams) error {
	_, err := q.db.Exec(ctx, saveEndpoint, arg.Slug, arg.CreatedAt)
	return err
}
