// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package infra

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DeliveryAttempt struct {
	ID              string
	RequestID       string
	Delivered       bool
	StatusCode      int32
	Error           string
	IsReplay        bool
	AttemptedAt     pgtype.Timestamptz
	ResponseBody    []byte
	ResponseHeaders []byte
}

type Endpoint struct {
	Slug      string
	CreatedAt pgtype.Timestamptz
}

type Request struct {
	ID          string
	Slug        string
	Method      string
	Path        string
	Headers     []byte
	QueryParams []byte
	Body        []byte
	SourceIp    string
	ReceivedAt  pgtype.Timestamptz
	BodySize    int32
}
