// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package infra

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRequest = `-- name: GetRequest :one
SELECT id, slug, method, path, headers, query_params, body, source_ip, received_at, body_size
FROM requests
WHERE id = $1
`

func (q *Queries) GetRequest(ctx context.Context, id string) (Request, error) {
	row := q.db.QueryRow(ctx, getRequest, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Method,
		&i.Path,
		&i.Headers,
		&i.QueryParams,
		&i.Body,
		&i.SourceIp,
		&i.ReceivedAt,
		&i.BodySize,
	)
	return i, err
}

const listLatestAttemptsBySlug = `-- name: ListLatestAttemptsBySlug :many
SELECT DISTINCT ON (da.request_id)
    da.id, da.request_id, da.delivered, da.status_code, da.error, da.is_replay, da.attempted_at,
    da.response_body, da.response_headers
FROM delivery_attempts da
JOIN requests r ON da.request_id = r.id
WHERE r.slug = $1
ORDER BY da.request_id, da.attempted_at DESC
`

func (q *Queries) ListLatestAttemptsBySlug(ctx context.Context, slug string) ([]DeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, listLatestAttemptsBySlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryAttempt
	for rows.Next() {
		var i DeliveryAttempt
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Delivered,
			&i.StatusCode,
			&i.Error,
			&i.IsReplay,
			&i.AttemptedAt,
			&i.ResponseBody,
			&i.ResponseHeaders,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequests = `-- name: ListRequests :many
SELECT id, slug, method, path, headers, query_params, body, source_ip, received_at, body_size
FROM requests
WHERE slug = $1
ORDER BY received_at DESC
`

func (q *Queries) ListRequests(ctx context.Context, slug string) ([]Request, error) {
	rows, err := q.db.Query(ctx, listRequests, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Method,
			&i.Path,
			&i.Headers,
			&i.QueryParams,
			&i.Body,
			&i.SourceIp,
			&i.ReceivedAt,
			&i.BodySize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveDeliveryAttempt = `-- name: SaveDeliveryAttempt :exec
INSERT INTO delivery_attempts (id, request_id, delivered, status_code, error, is_replay, attempted_at, response_body, response_headers)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type SaveDeliveryAttemptParams struct {
	ID              string
	RequestID       string
	Delivered       bool
	StatusCode      int32
	Error           string
	IsReplay        bool
	AttemptedAt     pgtype.Timestamptz
	ResponseBody    []byte
	ResponseHeaders []byte
}

func (q *Queries) SaveDeliveryAttempt(ctx context.Context, arg SaveDeliveryAttemptParams) error {
	_, err := q.db.Exec(ctx, saveDeliveryAttempt,
		arg.ID,
		arg.RequestID,
		arg.Delivered,
		arg.StatusCode,
		arg.Error,
		arg.IsReplay,
		arg.AttemptedAt,
		arg.ResponseBody,
		arg.ResponseHeaders,
	)
	return err
}

const saveRequest = `-- name: SaveRequest :exec
INSERT INTO requests (id, slug, method, path, headers, query_params, body, source_ip, received_at, body_size)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type SaveRequestParams struct {
	ID          string
	Slug        string
	Method      string
	Path        string
	Headers     []byte
	QueryParams []byte
	Body        []byte
	SourceIp    string
	ReceivedAt  pgtype.Timestamptz
	BodySize    int32
}

func (q *Queries) SaveRequest(ctx context.Context, arg SaveRequestParams) error {
	_, err := q.db.Exec(ctx, saveRequest,
		arg.ID,
		arg.Slug,
		arg.Method,
		arg.Path,
		arg.Headers,
		arg.QueryParams,
		arg.Body,
		arg.SourceIp,
		arg.ReceivedAt,
		arg.BodySize,
	)
	return err
}
